/* Fictional, deterministic private-credit example. No client data or live requests. */
(() => {
  'use strict';
  const motion = window.matchMedia('(prefers-reduced-motion: reduce)');
  const loans = [
    ['Arno Components','Industrials',24000000,660000,60000,54000000,12000000,5],
    ['Pitti Packaging','Packaging',20000000,550000,40000,48000000,10000000,5],
    ['Fiesole Software','Software',18000000,495000,30000,36000000,9000000,5],
    ['Bardi Logistics','Logistics',16000000,440000,20000,28000000,8000000,4.5],
    ['Cascine Healthcare','Healthcare',12000000,330000,0,32000000,8000000,5],
    ['Strozzi Services','Business services',10000000,275000,0,30000000,6000000,5.5]
  ].map(([name,sector,principal,cash,pik,netDebt,ebitda,limit])=>({name,sector,principal,cash,pik,netDebt,ebitda,limit,leverage:netDebt/ebitda}));
  const sum = key => loans.reduce((total,row)=>total+row[key],0);
  // Principal movements are separate from interest; current-quarter PIK is uncapitalized.
  const principalMovements = [[25000000,0,1000000],[19000000,2000000,1000000],[18000000,0,0],[17000000,0,1000000],[12000000,0,0],[9000000,2000000,1000000]];
  const movementTotal = index => principalMovements.reduce((total,row)=>total+row[index],0);
  const money = n => '$'+n.toLocaleString('en-US');
  const millions = n => '$'+(n/1000000).toFixed(2)+'m';
  const ratio = n => n.toFixed(2)+'×';
  const cite = (source,label) => `<button type="button" class="re-citation" data-source="${source}" aria-label="Inspect source: ${label}">${label} ↗</button>`;
  const table = (head,rows) => `<div class="re-document-table"><table><thead><tr>${head.map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map((v,i)=>i===0?`<th scope="row">${v}</th>`:`<td>${v}</td>`).join('')}</tr>`).join('')}</tbody></table></div><p class="re-table-scroll-hint" hidden>Scroll the table sideways to see all columns →</p>`;
  const metrics = items => `<div class="re-document-metrics">${items.map(([label,value])=>`<div><span>${label}</span><strong>${value}</strong></div>`).join('')}</div>`;
  const note = text => `<p class="re-document-note">${text}</p>`;
  const ledgerRows = loans.map(p=>[p.name,money(p.principal),money(p.cash),money(p.pik)]);
  const covenantRows = loans.map(p=>[p.name,money(p.netDebt),money(p.ebitda),ratio(p.leverage),ratio(p.limit)]);
  const principalRows = loans.map((p,index)=>[p.name,...principalMovements[index].map(money),money(p.principal)]).concat([['Total',money(movementTotal(0)),money(movementTotal(1)),money(movementTotal(2)),money(sum('principal'))]]);
  const principalTable = () => table(['Borrower','30 Jun principal','Q3 advances','Q3 repayments','30 Sep principal'],principalRows);
  const coverageRows = [['Financial statements','6','6','0'],['Signed certificates','6','5','1'],['Pitti adjustment support','1','0','1']];
  const coverageTable = () => table(['Required record','Expected','Received','Missing'],coverageRows);
  const pitti = loans.find(loan=>loan.name==='Pitti Packaging');
  const pittiBase = 9000000;
  const pittiClaimedAdjustment = 1000000;
  const pittiRequiredAdjustment = pitti.netDebt / pitti.limit - pittiBase;
  const pittiSensitivity = table(['Eligible adjustment, if confirmed','EBITDA used','Illustrative ratio'],[0,pittiRequiredAdjustment,pittiClaimedAdjustment].map(amount=>[money(amount),money(pittiBase+amount),ratio(pitti.netDebt/(pittiBase+amount))]));
  const pages = [
    {title:'Internal · credit summary',body:`<p class="re-document-eyebrow">Balances at 30 September · Review as of 17 November 2026</p><h2>Six credits.<br>Two questions to resolve.</h2>${metrics([['Principal outstanding',millions(sum('principal'))],['Cash interest received',millions(sum('cash'))],['Open items in this sample','2']])}<p>Fiorino Debt Partners holds six loans with $100 million of principal outstanding at 30 September. The servicing ledger records $2.75 million of cash interest received during Q3 and $150,000 of PIK accrued separately.</p>${cite(0,'Servicing ledger · Q3 balances and receipts')}<h3>Pitti: get the support behind the adjustment</h3><p>The borrower’s certificate adds $1 million of restructuring costs to $9 million of LTM EBITDA. That produces 4.80× net leverage against a supplied 5.00× maximum. The submission contains no supporting cost schedule. Excluding the adjustment gives 5.33×; the credit analyst needs to establish how much, if any, is eligible.</p>${cite(3,'Pitti financials · LTM EBITDA')} ${cite(4,'Pitti certificate · EBITDA bridge')} ${cite(6,'Submission manifest · missing support')}<h3>Bardi: obtain the signed certificate</h3><p>The financial statements have arrived. The compliance certificate has not, against the 16 November deadline in the supplied calendar. Portfolio operations has a draft reminder to review; no follow-up has been sent.</p>${cite(2,'Reporting tracker · 17 November status')}${note('Five internal working papers, followed by a separate investor draft on page 6. The sample covers the stated figures and two open items, not a complete credit assessment.')}`},
    {title:'Internal · loan book',body:`<p class="re-document-eyebrow">Exposure schedule · 30 September 2026</p><h2>Where the principal sits</h2><p>Arno Components is the largest position at 24% of principal outstanding. Together, Arno and Pitti Packaging account for 44%. The supplied loan master identifies all six positions as senior secured loans denominated in USD.</p>${table(['Borrower','Sector','Principal','Share'],loans.map(p=>[p.name,p.sector,money(p.principal),(p.principal/sum('principal')*100).toFixed(0)+'%']).concat([['Total','Six sectors',money(sum('principal')),'100%']]))}<div class="re-document-callout"><strong>Two largest positions: 44%</strong><p>($24 million + $20 million) ÷ $100 million.</p></div><h3>How principal moved this quarter</h3>${principalTable()}<p>Opening principal of $100m + $4m advanced − $4m repaid = $100m at quarter-end. These are principal movements only; cash interest and uncapitalized PIK sit in separate columns.</p><h3>Balance basis</h3><p>These are principal balances from the servicing ledger, not fair values, fund NAV, or total borrower debt. Current-quarter PIK is listed separately and has not been capitalized in the balances shown. The borrower net-debt figures used in the covenant worksheet come from a separate submission schedule.</p>${cite(0,'Servicing ledger · loan master and principal')} ${cite(1,'Submission schedule · borrower net debt')}${note('Exposure schedule only. No investment limit, risk rating, or concentration breach is inferred.')}`},
    {title:'Internal · Pitti & covenants',body:`<p class="re-document-eyebrow">Pitti Packaging · Worked borrower review · 17 November 2026</p><h2>One adjustment.<br>Two very different ratios.</h2><p>Pitti’s financials show $9 million of LTM EBITDA. Its compliance certificate adds $1 million of restructuring costs and reports $10 million of adjusted EBITDA. The supplied net debt is $48 million.</p>${cite(3,'Financials · page 8, LTM column')} ${cite(4,'Certificate · section 2, EBITDA bridge')}<h3>The missing piece</h3><p>The upload manifest lists the financials and signed certificate, but no restructuring-cost schedule. The credit analyst still needs the underlying costs and must check their treatment against the executed agreement.</p>${cite(6,'Submission manifest · attachment list')}<div class="re-document-callout re-document-exception"><strong>How much of the adjustment changes the result?</strong><p>At the supplied 5.00× maximum, EBITDA would need to be $48m ÷ 5.00 = $9.60m. Starting from $9m, that requires $0.60m of eligible adjustment under this simplified formula.</p>${pittiSensitivity}<p>The submitted $1m produces 4.80×. With none included, the result is 5.33×. These are conditional calculations—not a finding that any adjustment is permitted or that a covenant has been breached.</p></div>${cite(5,'Supplied terms · formula and maximum')}<h3>Credit analyst’s next step</h3><p>Obtain the cost schedule, check eligibility and caps, and confirm the agreement definitions, amendments, testing date, and any applicable cure provisions. The review stays open until the team resolves those points.</p><h3>All six submitted calculations</h3>${table(['Borrower','Net debt','LTM EBITDA','Ratio','Maximum'],covenantRows)}<p>Bardi’s 3.50× uses supplied financial-statement figures; its signed certificate is missing. The other ratios use the supplied submission schedule. None of these arithmetic results is a compliance certification.</p>${cite(1,'Submission schedule · all six loans')} ${cite(2,'Tracker · Bardi certificate status')}${note('Simplified fictional net-leverage tests. Other covenants, cash-netting verification, and agreement interpretation are outside this sample.')}`},
    {title:'Internal · cash interest & PIK',body:`<p class="re-document-eyebrow">Servicing activity · 1 July–30 September 2026</p><h2>Cash received.<br>PIK accrued.</h2>${metrics([['Cash interest received',millions(sum('cash'))],['PIK interest accrued',money(sum('pik'))],['Borrowers with PIK','4']])}${table(['Borrower','Principal at quarter-end','Cash interest received','PIK accrued'],ledgerRows.concat([['Total',money(sum('principal')),money(sum('cash')),money(sum('pik'))]]))}<p>Cash interest plus PIK accruals totals $2.90m, but only $2.75m is recorded as received cash. Arno, Pitti, Fiesole and Bardi account for all $150,000 of PIK.</p><p>The cash column records interest received in Q3. The PIK column records interest accrued without a cash receipt. Keeping them separate prevents non-cash accruals from appearing as money available to distribute.</p><h3>Reconciliation remains outside this sample</h3><p>These are supplied servicer amounts. Before using them in the fund report, reconcile them with administrator records and bank receipts, then add the approved fair values, expenses, fees, and investor allocations.</p>${cite(0,'Servicing ledger · cash and PIK columns')}${note('No bank or administrator reconciliation is represented here. These amounts are not a fund return, annualized yield, or distribution calculation; interest has not been independently recomputed from loan terms.')}`},
    {title:'Internal · follow-ups & sources',body:`<p class="re-document-eyebrow">Review queue · As of 17 November 2026</p><h2>Two open items.<br>Clear next steps.</h2>${coverageTable()}<p>Six of six financial statements and five of six signed certificates are on file. Pitti’s supporting schedule is a separate missing attachment, so there are two open items across two borrowers.</p>${table(['Borrower','Open item','Owner','Next step'],[['Pitti Packaging','Support for $1m restructuring adjustment','Credit analyst','Obtain cost schedule; check agreement treatment'],['Bardi Logistics','Certificate due 16 November','Portfolio operations','Review and send draft request to borrower CFO']])}<h3>Draft reminder to Bardi</h3><div class="re-document-callout"><strong>Subject: Q3 compliance certificate</strong><p>Hi Bardi team,</p><p>Thanks for sending the Q3 financial statements. We are still missing the compliance certificate due on 16 November. Please send the signed certificate, or let us know when we should expect it.</p><p>Thank you,<br>Fiorino Debt Partners</p></div><p>No email has been sent. The certificate is one calendar day overdue against this example’s supplied calendar. That is a document-tracking status, not a conclusion about default.</p>${cite(2,'Reporting tracker · owners and unsent status')}<h3>Supporting records</h3><ol class="re-source-register"><li><strong>Servicing ledger and loan master</strong><p>Six positions, sectors, principal, cash receipts, and PIK accruals.</p>${cite(0,'Open ledger and loan master')}</li><li><strong>Borrower submission schedule</strong><p>Supplied figures and thresholds for the six simplified tests.</p>${cite(1,'Open submission schedule')}</li><li><strong>Pitti’s original excerpts</strong><p>Separate financials, signed certificate, supplied terms extract, and submission manifest.</p>${cite(3,'Open financials')} ${cite(4,'Open certificate')} ${cite(5,'Open supplied terms')} ${cite(6,'Open attachment list')}</li><li><strong>Reporting tracker</strong><p>Due dates, received dates, document status, and review owners.</p>${cite(2,'Open reporting tracker')}</li></ol>${note('All records and commentary are fictional and prewritten. This illustrates a proposed workflow, not a live Cosimo run or a production-validated monitoring system.')}`},
    {title:'Separate draft · LP update',body:`<p class="re-document-eyebrow">Separate investor communication · Draft for approval</p><h2>Third-quarter portfolio update</h2><p>Dear Limited Partners,</p><p>Fiorino Debt Partners ended the third quarter with $100 million of principal outstanding across six senior secured loans. The book opened the quarter at $100 million, with $4 million advanced and $4 million repaid during Q3. Arno Components and Pitti Packaging were the two largest positions, representing 24% and 20% of principal respectively.</p><p>The servicing ledger records $2.75 million of cash interest received during the quarter and $150,000 of PIK accrued. PIK is non-cash and is presented separately from cash receipts. These amounts do not represent the fund’s net return or cash available for distribution.</p><p>As of 17 November, supporting detail for a restructuring adjustment in Pitti Packaging’s reported EBITDA remains outstanding. Bardi Logistics has supplied its financial statements; its compliance certificate remains outstanding.</p><p>Sincerely,<br>Fiorino Debt Partners</p><h3>Internal approval note — remove before distribution</h3><p>This proposed borrower commentary has not been cleared for external use. Confirm disclosure and confidentiality, reconcile the portfolio figures, and decide what belongs in the investor update. The internal covenant worksheet and follow-up queue are separate working papers.</p>${cite(0,'Servicing ledger · portfolio figures')} ${cite(6,'Manifest · missing adjustment support')} ${cite(2,'Tracker · certificate status')}${note('Illustrative portfolio commentary, not a complete fund performance report. Source buttons and the internal approval note are review tools, not part of the investor letter.')}`}
  ];
  function pageHTML(index) {
    return `<article class="re-document-page"><header><span class="re-paper-brand">Fiorino Debt Partners</span><span>Direct Lending Fund I<br>Q3 2026 · ${index !== 5 ? 'Internal review' : 'Investor draft'}</span></header>${pages[index].body}<footer><span>Fictional demonstration · Not for distribution</span><span>${String(index+1).padStart(2,'0')} / 06</span></footer></article>`;
  }
  const sources = [
    {name:'Fiorino_Debt_Partners_Loan_Ledger_Q3.xlsx',html:`<p class="re-source-caption">Fictional servicer export · v1 received 13 November 2026 · Sheets: Loan master / Principal movements / Q3 activity</p><h3>Loan master · rows 2–7</h3>${table(['Borrower','Sector','Security','Currency'],loans.map(p=>[p.name,p.sector,'Senior secured','USD']))}<h3>Principal movements · 1 July–30 September · USD</h3>${principalTable()}<h3>Q3 interest activity · rows 2–7 · USD</h3>${table(['Borrower','Principal outstanding','Cash interest received','PIK accrued'],ledgerRows.concat([['Total',money(sum('principal')),money(sum('cash')),money(sum('pik'))]]))}<p>Principal balances: 30 September 2026. Cash receipts and PIK accruals: 1 July–30 September. Current-quarter PIK has not been capitalized in these balances. No bank reconciliation, fair values, expenses, or fund-level returns are supplied.</p>`},
    {name:'Borrower_Submission_Schedule_Q3.xlsx',html:`<p class="re-source-caption">Fictional supplied schedule · v1 received 16 November 2026 · Sheet: Net leverage, rows 2–7</p>${table(['Borrower','Net debt supplied','LTM EBITDA supplied','Maximum supplied'],loans.map(p=>[p.name,money(p.netDebt),money(p.ebitda),ratio(p.limit)]))}<p>Testing date: 30 September 2026. Supplied worksheet formula: net debt ÷ LTM EBITDA. Net debt is provided after borrower-reported cash netting; that netting has not been independently verified in this sample.</p><p>Pitti’s $10m EBITDA ties to its certificate’s adjusted figure; open the original financials and bridge below. Bardi’s figures come from its financials because its certificate has not arrived. This schedule contains supplied inputs, not compliance conclusions.</p>${cite(3,'Pitti financials · page 8')} ${cite(4,'Pitti certificate · section 2')} ${cite(5,'Pitti terms extract · test 1')}`},
    {name:'Borrower_Reporting_Tracker.xlsx',html:`<p class="re-source-caption">Fictional reporting calendar · v2, 17 November 2026 · Sheet: Q3 submissions</p>${table(['Borrower','Certificate due','Certificate received','Financials'],[['Arno Components','16 November','12 November','Received'],['Pitti Packaging','16 November','13 November','Received'],['Fiesole Software','16 November','12 November','Received'],['Bardi Logistics','16 November','Not received','Received 13 November'],['Cascine Healthcare','16 November','12 November','Received'],['Strozzi Services','16 November','13 November','Received']])}<h3>Document coverage · as of 17 November</h3>${coverageTable()}<h3>Review queue · rows 10–11</h3>${table(['Borrower','Owner','Next action','Action status'],[['Pitti Packaging','Credit analyst','Request restructuring cost schedule; check agreement treatment','Pending — no request sent'],['Bardi Logistics','Portfolio operations','Request signed compliance certificate','Draft only — not sent']])}<p>The deadline is the calendar supplied for this fictional example, not a standard reporting deadline. Bardi’s certificate is <mark>one calendar day overdue</mark> as of 17 November.</p>`},
    {name:'Pitti_Financials_2026-09.pdf',html:`<p class="re-source-caption">Fictional borrower financials · v1 received 13 November 2026 · Page 8, LTM summary · USD</p><h3>Pitti Packaging · Twelve months ended 30 September 2026</h3>${table(['Financial statement line','LTM amount'],[['Revenue','$72,000,000'],['Operating costs before depreciation and amortization','($63,000,000)'],['EBITDA before certificate adjustments',money(pittiBase)]] )}<p>Excerpt basis: management financials, USD, LTM to 30 September. These lines precede the separate adjustments claimed in the compliance certificate. The excerpt does not establish which adjustments the loan agreement permits.</p>`},
    {name:'Pitti_Compliance_Certificate_Q3.pdf',html:`<p class="re-source-caption">Fictional borrower certificate · Signed 12 November; received 13 November 2026 · Section 2, leverage calculation · USD</p><h3>Borrower-submitted EBITDA bridge</h3>${table(['Certificate line','Submitted amount'],[['LTM EBITDA before adjustments',money(pittiBase)],['Restructuring cost adjustment',money(pittiClaimedAdjustment)],['Adjusted LTM EBITDA',money(pitti.ebitda)],['Net debt after reported cash netting',money(pitti.netDebt)],['Net leverage reported',ratio(pitti.leverage)]])}<p>Certificate attachment reference: “Restructuring costs — Schedule A.” The certificate supplies the amount; it does not show the underlying costs in this excerpt. Check the attachment list to see what was received.</p>${cite(6,'Submission manifest · received attachments')}`},
    {name:'Pitti_Supplied_Terms_Extract.xlsx',html:`<p class="re-source-caption">Fictional analyst-supplied terms extract · v1 dated 10 November 2026 · Sheet: Tests, row 1</p>${table(['Field','Supplied term'],[['Testing date','30 September 2026'],['Calculation','Net debt ÷ LTM EBITDA'],['Maximum ratio','5.00×'],['Adjustment treatment','Check executed agreement and supporting costs']])}<p>This is a limited terms extract supplied for the example, not an executed agreement or legal interpretation. It supplies the formula and maximum used in the sensitivity. Definitions, eligibility, adjustment caps, amendments, cash netting, cure rights, and other covenants still require credit-team review.</p>`},
    {name:'Pitti_Submission_Manifest_2026-11-17.txt',html:`<p class="re-source-caption">Fictional submission record · Updated 17 November 2026 · Attachment list for 13 November borrower delivery</p>${table(['Attachment named in submission','Received'],[['Pitti_Financials_2026-09.pdf','13 November · v1'],['Pitti_Compliance_Certificate_Q3.pdf','13 November · signed 12 November'],['Schedule A — restructuring costs','No file received']])}<h3>Borrower cover message · 13 November</h3><div class="re-proof-note-paper"><p>Attached are the September financials and signed Q3 compliance certificate. We will send the restructuring cost detail separately.</p></div><p>No subsequent support file is recorded as of 17 November. This establishes a missing attachment, not whether any particular cost is eligible under the agreement.</p>`}
  ];
  const sourceCard = (kind,name,index,body)=>`<div class="re-proof-source"><div class="re-proof-card-heading"><div><span class="re-proof-role">Your records</span><h4>${kind}</h4></div><button type="button" data-source="${index}">View source ↗</button></div><p class="re-proof-filename">${name}</p>${body}</div>`;
  const resultCard = (title,body,index,label)=>`<div class="re-proof-result"><div class="re-proof-card-heading"><div><span class="re-proof-role">${index !== 5 ? 'For your team' : 'For your investors'}</span><h4>${title}</h4></div><span class="re-proof-r" aria-hidden="true">F</span></div>${body}<button type="button" class="re-proof-page-link" data-report-page="${index}">${label} <span aria-hidden="true">↗</span></button></div>`;
  const story = (n,title,detail,content)=>`<article class="re-proof-story"><div class="re-proof-story-heading"><span aria-hidden="true">0${n}</span><div><h3>${title}</h3><p>${detail}</p></div></div><div class="re-proof-comparison">${content}<div class="re-proof-connector" aria-hidden="true"><i></i><span>→</span></div></div></article>`;
  document.getElementById('report-proof-scenes').innerHTML = [
    story(1,'The certificate says 4.80×. What supports it?','Bring the financials, adjustment, and supplied limit into the same review.',
      sourceCard('Pitti’s financials and certificate','Two borrower files · Received 13 November',4,`<div class="re-proof-note-paper"><span>Financials · LTM to 30 September</span><p>EBITDA before adjustments: <strong>$9m</strong></p><span>Certificate · EBITDA bridge</span><p>Restructuring adjustment: <strong>+$1m</strong></p><p>Adjusted EBITDA: <strong>$10m</strong> · Net debt: <strong>$48m</strong></p></div>${cite(3,'Inspect financials')} ${cite(5,'Inspect 5.00× supplied limit')}<p class="re-proof-source-caption">The certificate names a cost schedule. The attachment list shows <mark>no file received</mark>.</p>${cite(6,'Inspect attachment list')}`)+
      resultCard('The adjustment needs support',`<div class="re-proof-big-figures"><div><span>With the claimed adjustment</span><strong>4.80×</strong><small>$48m ÷ $10m</small></div><div><span>With no adjustment</span><strong>5.33×</strong><small>$48m ÷ $9m</small></div></div><div class="re-proof-review-flag"><span>Open · Credit analyst</span><strong>At least $0.60m would need to qualify.</strong><p>Under the supplied formula, $9.60m of EBITDA gives 5.00×. Obtain the costs and check how much the agreement permits.</p></div><p class="re-proof-trace">Conditional sensitivity. The calculation does not decide compliance.</p>`,2,'Inspect the Pitti review')),
    story(2,'Keep non-cash income out of the cash total.','A portfolio summary should preserve the distinction your servicer makes.',
      sourceCard('Servicing ledger','Fiorino_Debt_Partners_Loan_Ledger_Q3.xlsx',0,`<p class="re-proof-sheet-note">All six loans · Q3 activity · USD</p>${table(['Borrower','Cash received','PIK accrued'],loans.map(p=>[p.name,money(p.cash),money(p.pik)]).concat([['Total',money(sum('cash')),money(sum('pik'))]]))}<p class="re-proof-source-caption">Quarter-end principal is recorded separately. Current-quarter PIK has not been capitalized.</p>`)+
      resultCard('Two totals. Two meanings.',`<div class="re-proof-big-figures"><div><span>Cash interest received</span><strong>$2.75m</strong><small>All six loans · Q3 receipts</small></div><div><span>PIK interest accrued</span><strong>$150k</strong><small>All six loans · Non-cash</small></div></div><blockquote>“The servicing ledger records $2.75 million of cash interest received during the quarter and $150,000 of PIK accrued.”</blockquote><p class="re-proof-trace">Servicer amounts only. Bank and administrator reconciliation is not included in this sample.</p>`,3,'Inspect the cash and PIK schedule')),
    story(3,'The financials arrived. The certificate did not.','Carry the missing document into an owned follow-up, without marking the review complete.',
      sourceCard('Bardi’s reporting record','Borrower_Reporting_Tracker.xlsx',2,`${table(['Bardi Logistics','Status'],[['Q3 financials','Received 13 November'],['Compliance certificate','Not received'],['Supplied due date','16 November 2026'],['Review date','17 November 2026']])}<p class="re-proof-source-caption">Five of six certificates received. One calendar day overdue against the supplied calendar.</p>`)+
      resultCard('A reminder for operations to review',`<p class="re-proof-report-label">To the Bardi finance team · Draft</p><blockquote>“Thanks for sending the Q3 financial statements. We are still missing the compliance certificate due on 16 November. Please send the signed certificate, or let us know when we should expect it.”</blockquote><div class="re-proof-review-flag"><span>Owner · Portfolio operations</span><strong>Review the request. Keep the item open.</strong><p>No email has been sent. The certificate still needs to arrive and be reviewed.</p></div>`,4,'Inspect the follow-up queue'))
  ].join('');

  const reader = document.getElementById('sample-lp-report');
  const sourceDialog = document.getElementById('report-source');
  const chapters = document.getElementById('reader-chapters');
  let readerPage = 0;
  const chapterAudience = index => index < 5 ? 'Internal review' : 'Investor draft';
  chapters.innerHTML = pages.map((page,index)=>`${index === 0 || chapterAudience(index) !== chapterAudience(index-1) ? `<p class="re-chapter-group">${chapterAudience(index)}</p>` : ''}<button type="button" data-page="${index}" aria-controls="full-report-content"><span>0${index+1}</span><span>${page.title.replace(/^(Internal · |Separate draft · )/,'')}</span></button>`).join('');
  function updateTableHints() {
    document.querySelectorAll('.re-document-table').forEach(element=>{
      const overflows = element.scrollWidth > element.clientWidth + 1;
      element.nextElementSibling.hidden = !overflows;
      if (overflows) {
        element.setAttribute('tabindex','0');
        element.setAttribute('aria-label','Scrollable data table');
      } else {
        element.removeAttribute('tabindex');
        element.removeAttribute('aria-label');
      }
    });
  }
  window.addEventListener('resize', updateTableHints);
  function renderReader(index, moveToReader=false) {
    readerPage = index;
    document.getElementById('full-report-content').innerHTML = pageHTML(index);
    document.getElementById('reader-page-number').textContent = `Page ${index+1} of ${pages.length}`;
    chapters.querySelectorAll('[data-page]').forEach(button=>button.setAttribute('aria-current',String(Number(button.dataset.page)===index)));
    document.getElementById('reader-prev').disabled = index===0;
    document.getElementById('reader-next').disabled = index===pages.length-1;
    document.getElementById('reader-next-bottom').disabled = index===pages.length-1;
    updateTableHints();
    if (moveToReader) {
      // A chapter selected halfway down the previous page must start at its own top.
      const readingPane = document.getElementById('reader-body');
      const heading = document.querySelector('#full-report-content h2');
      readingPane.scrollIntoView({behavior:motion.matches?'instant':'smooth',block:'start'});
      heading.tabIndex = -1;
      heading.focus({preventScroll:true});
    }
  }
  function showSource(index) {
    document.getElementById('source-filename').textContent = sources[index].name;
    document.getElementById('source-content').innerHTML = sources[index].html;
    if (!sourceDialog.open) sourceDialog.showModal();
    updateTableHints();
  }
  document.addEventListener('click',event=>{
    const source = event.target.closest('[data-source]');
    if (source) showSource(Number(source.dataset.source));
    const reportPage = event.target.closest('[data-report-page]');
    if (reportPage) renderReader(Number(reportPage.dataset.reportPage),true);
  });
  chapters.addEventListener('click',event=>{
    const button=event.target.closest('[data-page]');
    if (button) renderReader(Number(button.dataset.page),true);
  });
  document.getElementById('reader-prev').addEventListener('click',()=>renderReader(Math.max(0,readerPage-1),true));
  document.getElementById('reader-next').addEventListener('click',()=>renderReader(Math.min(pages.length-1,readerPage+1),true));
  document.getElementById('reader-next-bottom').addEventListener('click',()=>renderReader(Math.min(pages.length-1,readerPage+1),true));
  document.getElementById('close-source').addEventListener('click',()=>sourceDialog.close());
  sourceDialog.addEventListener('click',event=>{
    if(event.target!==sourceDialog)return;
    const r=sourceDialog.getBoundingClientRect();
    if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)sourceDialog.close();
  });
  document.querySelectorAll('a[href="#sample-lp-report"]').forEach(link=>link.addEventListener('click',()=>{
    renderReader(0);reader.focus({preventScroll:true});
  }));
  renderReader(0);
  // The data is always visible. Motion only traces an existing relationship,
  // once per comparison, without timed page changes or scroll capture.
  const proofObserver = new IntersectionObserver(entries=>{
    entries.forEach(entry=>{
      if (!entry.isIntersecting) return;
      entry.target.classList.add('is-observed');
      proofObserver.unobserve(entry.target);
    });
  },{threshold:.2});
  document.querySelectorAll('.re-proof-comparison').forEach(element=>proofObserver.observe(element));
})();
